### date:2021年11月29日
### author: www.mrdoc.fun | jonnyan404
### 转载请保留来源
### update：2022年08月14日
version: '2.0'
services:
    ztncui:
        container_name: zerotier_planet
        restart: always
        environment:
            - MYADDR=2.2.2.2 #改成自己的服务器公网IP,可修改 
            - HTTP_PORT=4000       #docker 内部web端口
            - HTTP_ALL_INTERFACES=yes
            - ZTNCUI_PASSWD=admin123456  #用户admin的密码，登录后需设置其他密码,可修改 
            - MYADDR_PORT=8882     #给moon用的外部端口,可修改 
        ports:
            - '8881:4000' # web控制台入口,可修改 
            - '8882:9993' # 冒号前面是宿主机的端口,可修改 
            - '8882:9993/udp'# 可修改 
            - '8883:3180' # planet/moon文件在线下载入口，如不对外提供。可防火墙禁用此端口。,可修改 
        volumes:
            - './zerotier-one:/var/lib/zerotier-one'
            - './ztncui/etc:/opt/key-networks/ztncui/etc'
            # 按实际路径挂载卷， 冒号前面是宿主机的， 支持相对路径
        image: feko2022/zerotier_planet:v2.0
